### ISSUE TITLE
Имена веток

### ISSUE THREAD

**Issue by iandreyshev** [RoboutGulman/RRW_Flutter#5]
Пожалуйста, сделайте осознанные имена у веток.

Пусть будет ветка **master (или main)**, в которой будет находиться последняя живая версия - версия, которая будет результатом работы за итерацию. Эта версия должна корректно собираться и работать

Когда хотите сделать изменения, каждый заводит отдельную ветку. Ветку можно назвать либо по номеру Issue, либо просто на английском по тому, что хотите в ней сделать

После реализации в отдельной ветке собирается ветка с несколькими изменениями, после чего версия мержится в master.

Нужно посмотреть инфу про Git-Flow

**Comment by yogrr** [comment]
alex - Алексей
steve - Рафаиль

Ветки для изменений в следующем формате:
alex_issue1
steve_authorization

Так пойдёт?

**Comment by iandreyshev** [comment]
По коммиту можно увидеть, кто его делает
![image](https://user-images.githubusercontent.com/22149746/130756843-5ed00607-5507-4525-be79-e7fa03fec555.png)

Ветки стоит называть по задаче, которая в ней выполняется
Ветка master содержит последнюю рабочую версию, в которую слиты все закрытые задачи на данный момент
Задача выполнена -> ветка сливается в master

**Comment by yogrr** [comment]
Ок, поняли
